graph LR
    SONARQUBE(SonarQube) --> |metrics data| CSV>CSV]
    CSV --> DASHBOARD(Dashboard)
    subgraph DashboardApp
        DASHBOARD --> |analyze| Z-SCORE[z-score]
        DASHBOARD --> |analyze| STATISTICS[Statistics]
    end