# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages
r:
- release
- devel

addons:
  apt:
    packages:
    - pkg-config
    - libssl-dev
    - libcurl4-openssl-dev
    - libxml2-dev
    - libnlopt-dev

before_install:
  - cd app
