[sonarqube]
  url = "http://localhost:9000"
  resource = "063285ca8e14"
  metrics = [
    "time",
    "alert_status",
    "blocker_violations",
    "bugs",
    "class_complexity",
    "classes",
    "code_smells",
    "comment_lines",
    "comment_lines_density",
    "commit.id",
    "complexity",
    "complexity_in_classes",
    "complexity_in_functions",
    "confirmed_issues",
    "coverage",
    "critical_violations",
    "development_cost",
    "directories",
    "duplicated_blocks",
    "duplicated_files",
    "duplicated_lines",
    "duplicated_lines_density",
    "effort_to_reach_maintainability_rating_a",
    "false_positive_issues",
    "file_complexity",
    "file_complexity_distribution",
    "files",
    "function_complexity",
    "function_complexity_distribution",
    "functions",
    "info_violations",
    "last_commit_date",
    "line_coverage",
    "lines",
    "lines_to_cover",
    "major_violations",
    "minor_violations",
    "ncloc",
    "ncloc_language_distribution",
    "open_issues",
    "quality_gate_details",
    "quality_profiles",
    "reliability_rating",
    "reliability_remediation_effort",
    "reopened_issues",
    "security_rating",
    "security_remediation_effort",
    "skipped_tests",
    "sqale_debt_ratio",
    "sqale_index",
    "sqale_rating",
    "statements",
    "test_errors",
    "test_execution_time",
    "test_failures",
    "test_success_density",
    "tests",
    "uncovered_lines",
    "url",
    "violations",
    "vulnerabilities",
    "wont_fix_issues"
  ]
